#!/bin/sh
setxkbmap us,hu -variant ,qwerty
xrandr --output eDP --set TearFree on &
numlockx on &
xrdb "$XDG_CONFIG_HOME/Xresources"
xset r rate 300 30
xset -b
brightnessctl g > "$XDG_RUNTIME_DIR/brightness"
xkb-switch -p > "$XDG_RUNTIME_DIR/layout"

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
dunst &
picom &
unclutter &
nm-applet &
blueman-applet &
exec i3 >/dev/null 2>&1
