#!/bin/sh
setxkbmap us,hu -variant ,qwerty -model pc105 -option "caps:swapescape"
xrandr --output eDP --set TearFree on &
numlockx on &
xrdb "$XDG_CONFIG_HOME/Xresources"
xset r rate 300 30
xset -b
brightnessctl g > "$XDG_RUNTIME_DIR/brightness"
xkb-switch -p | cut -c 1-2 > "$XDG_RUNTIME_DIR/layout"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 >/dev/null 2>&1 &
/usr/lib/geoclue-2.0/demos/agent >/dev/null 2>&1 &
nitrogen --restore >/dev/null 2>&1 &
dunst >/dev/null 2>&1 &
picom --experimental-backends >/dev/null 2>&1 &
unclutter >/dev/null 2>&1 &
nm-applet >/dev/null 2>&1 &
blueman-applet >/dev/null 2>&1 &
redshift-gtk >/dev/null 2>&1 &
clipmenud >/dev/null 2>&1 &

exec i3 >/dev/null 2>&1
# slstatus >/dev/null 2>&1 &
# exec dwm >/dev/null 2>&1
